### ISSUE TITLE
Problem with styling on order page in admin.

### ISSUE THREAD

**Issue by marcwales** [mollie/Magento#103]
Magento 1.9.3.3
Ultimo theme 1.18.1
Mollie 5.0.4

Hi,
After upgrading from 4.5.3 to 5.0.4, the styling on the order page ("payment information" on admin side) is broken. The credit card logo is very big and the text is not aligned proprely. Here is a screenshot of the error on 5.0.4 and a second one on 4.5.3 to show you the difference. I've forced the cache and re-compile.

Thank you for your help.
Rgds, 
Marc

![mollie-4-5-3](https://user-images.githubusercontent.com/24587353/51374824-7481e600-1b04-11e9-8a90-8ff95cf1ab05.png)
![mollie-5-0-4](https://user-images.githubusercontent.com/24587353/51374826-751a7c80-1b04-11e9-9542-3743eb8717a0.png)

**Comment by Frank-Magmodules** [comment]
Hi @marcwales ,
Thanks for your feedback. The styling is correct this way, we have changed this to make the user interface more user-friendly.

**Comment by marcwales** [comment]
Hi Frank, thank you for your fast response. I'm afraid my screenshot are confusing because it doesn't show the version ;)
- The first one is to show you how it should be (this is a live screen of mollie 4.5.3 on magento 1.9.3.3)
- The second screenshot shows the problem of alignement on mollie 5.0.4. You can see that the words : payment and Paid are far to the right. I'm missing "transaction name", "card type". It looks like the translation is wrong to. I'm going to check the french version.

I've put the screenshot with the problem again in this post to avoid confusing. 

Rgds, 
Marc

![51374826-751a7c80-1b04-11e9-9542-3743eb8717a0](https://user-images.githubusercontent.com/24587353/51381425-6b007a00-1b14-11e9-8e8a-31ec66c5af85.png)

**Comment by Frank-Magmodules** [comment]
HI @marcwales. All clear, we've changed the way the payment details are showing. So the way your screenshot shows the payment information is right.

**Comment by marcwales** [comment]
Hi Frank, thank you for your fast response. Ok for this change, i think i'll work on the css to make it look better. It's doesn't look as professionnal as before ;) 
Rgds, 
Marc
