### ISSUE TITLE
More values for description ? 

### ISSUE THREAD

**Issue by marcwales** [mollie/Magento#117]
Hi, 
Love the new feature of being able to configure the description dynamically. Can i use more variables like "company name" or "clients name" ? Or is the value {ordernumber} and {storename} the only one for now ? 
Rgds, 
Marc

**Comment by Marvin-Magmodules** [comment]
At this moment only {ordernumber} and {storename} are supported, see: [Data.php#L897](https://github.com/mollie/Magento/blob/master/app/code/community/Mollie/Mpm/Helper/Data.php#L897). We can look into this to get more variables available. What variables would be useful to add?

**Comment by marcwales** [comment]
Hi Marvin, 
Thank you for your fast response. It would be great to retrieve the "company" if the client add it and the "billing name". Because if the client use a different name on the credit card info, it will be more difficult for the account to retrieve the payment amount.

**Comment by Frank-Magmodules** [comment]
Hi @marcwales  , we now have the following values available in the [latest release](https://github.com/mollie/Magento/releases) for the Payment-API description;

{ordernumber}: The order number for this transaction.
{storename}: The name of the store.
{customerCompany}: The name of the company of the customer. Can be empty.
{customerName}: The name on the billing address. Includes first, middle and last when available.

We are closing this issue now but please feel free to reopen the issue if this still occurs.
