### ISSUE TITLE
Payment not working after upgrade to 5.2

### ISSUE THREAD

**Issue by marcwales** [mollie/Magento#118]
Hi,
I've updated the mollie module on magento 1 to 5.2 and now the clients receive an error after payment. It says : "an error occured while processing the payment, please try again with another method". 
The payment goes through, i receive the amount but the client doesn't know it and retry sererall times. And the statuts stays on pending. 
Hope you can help me soon because this is urgent. 
Rgds, 
Marc

**Comment by Marvin-Magmodules** [comment]
Hi @marcwales,  can you contact us through our [contact form](https://www.magmodules.eu/contact-us.html) so we can exchange log files to check the issue?

**Comment by Marvin-Magmodules** [comment]
Issue has been fixed, was due to Magento’s Cache (System -> Cache Management) being disabled while updating the module. This can cause the setup script to run before it has been uploaded.
