### ISSUE TITLE
Creditmemo gone after on invoice after update to 5.3.0

### ISSUE THREAD

**Issue by albsa** [mollie/Magento#123]
Hi guys,

It doesn't seem possible to create a credit none anymore on the invoice, we updated from 4.+ to 5.3.0, any other way to create a refund from within Magento?

**Comment by albsa** [comment]
Magento version 1.9.4.0

**Comment by Marvin-Magmodules** [comment]
Hi @albsa there should be a button when opening the invoice [Credit Memo] to create an online invoice. The invoice has the status paid?

**Comment by albsa** [comment]
@Marvin-Magmodules the credit memo button is gone when upgrading from v4 to v5. I downgraded to v4 again and the credit memo button showed up again on the invoice.

I think the reason is that old invoices cant be credited is because the old methods are not able to refund.

**Comment by Frank-Magmodules** [comment]
Hi @albsa, 

We have just issued a release that fixes this issue, see [v5.5.1](https://github.com/mollie/Magento/releases/tag/v5.5.1). This will enable you to create online (and offline) refunds for orders placed on pre-v4.5. We are closing this issue now but please feel free to reopen the issue if this still occurs.
