### ISSUE TITLE
Order lines total

### ISSUE THREAD

**Issue by michael85a** [mollie/Magento#137]
in case we have an order which have discount
![image](https://user-images.githubusercontent.com/7724437/63145790-6136ea80-c001-11e9-9293-6544e9a4d9c1.png)
for example total is 56.91

in order lines table we have following data:
![image](https://user-images.githubusercontent.com/7724437/63146199-cfc87800-c002-11e9-9cc9-2db7f29c0bbb.png)
total in order lines is 56.9

that's why we are receiving following errors from api:

> DEBUG (7): error: Error executing API call (422: Unprocessable Entity): The amount of the order does not match the total amount from the order lines. Expected order amount to be â<82>¬56.90 but got â<82>¬56.91. Field: amount. Documentation: https://docs.mollie.com/guides/handling-errors

in request we have following data:
>  request: {"amount":{"currency":"EUR","value":"56.91"},

problem is in 2 digits after coma which is added to order lines or we have to take amount from order in that case it will be 56.9

**Comment by Frank-Magmodules** [comment]
HI @michael85a ,

Thank you for opening this issue, we will investigate this and we will come back to you on this shortly.

**Comment by Frank-Magmodules** [comment]
Hi @michael85a ,

Which Magento version are you using at the moment?

Frank

**Comment by Frank-Magmodules** [comment]
HI @michael85a , I've didn't' received a message on this anymore but this is a known issue in Magento 1.7.0.2. We've made a fix for this in the upcoming release which is going to be released next week.

**Comment by michael85a** [comment]
perfect

**Comment by Frank-Magmodules** [comment]
Hi @michael85a,

We have just issued a release that fixes this issue, see [v5.5.1](https://github.com/mollie/Magento/releases/tag/v5.5.1). This issue can occur when a large discount is given on the order, this can cause issues in the tax calculation. We are closing this issue now but please feel free to reopen the issue if this still occurs.
