### ISSUE TITLE
crediting of full order when fee have fee amount

### ISSUE THREAD

**Issue by michael85a** [mollie/Magento#141]
we have following situation:
Magento ver. 1.9.3.2
millie 5.5.0

when you credit full order is runned
Mollie_Mpm_Model_Client_Orders::createOrderRefund

![image](https://user-images.githubusercontent.com/7724437/64865689-8b9cb780-d642-11e9-9de6-57fdaf616a26.png)

\lib\Mollie\Mollie\src\Resources\Order.php

>     
    public function refundAll(array $data = [])
    {
        $data['lines'] = [];
        return $this->refund($data);
    }

in mollie account we can see that there is paid  9,90

but refund is just € 6,95
so fee is not refunded 

![image](https://user-images.githubusercontent.com/7724437/64866197-a0c61600-d643-11e9-89b4-a41476594f82.png)

![image](https://user-images.githubusercontent.com/7724437/64865996-44fb8d00-d643-11e9-92af-833c51043a45.png)

in case if partly refund it will work

**Comment by Marvin-Magmodules** [comment]
Hi @michael85a can you send me a screenshot of the order by email, as I'm not sure where this €2,95 is coming from?

**Comment by michael85a** [comment]
@Marvin-Magmodules 
2.95 is surcharge 
table mollie_order_lines look like this:

![image](https://user-images.githubusercontent.com/7724437/64868564-454a5700-d648-11e9-8333-f4ce162a8218.png)

**Comment by Marvin-Magmodules** [comment]
Hi @michael85a thank you, will try to reproduce this issue and look into this.

**Comment by michael85a** [comment]
@Marvin-Magmodules , thanks
but i think it has to do something with mollie itself

**Comment by Frank-Magmodules** [comment]
Hi @michael85a ,

I'm not able to reproduce this issue as the module does not allow surcharging of iDEAL payments. I've tried this flow with Klarna and surcharging, but also was not able to reproduce this as a full refund did refund the complete order including the payment fee. 

How did you add this surcharge fee to the iDEAL order?

**Comment by michael85a** [comment]
![image](https://user-images.githubusercontent.com/7724437/64946441-8fffe500-d87b-11e9-92c6-67c71d8179bb.png)


in order lines

**Comment by Frank-Magmodules** [comment]
Hi @michael85a. 

As this is something you implemented yourself it is pretty hard for me to debug this and give you any support on this (based on just a screenshot). However a quick look at your screenshot tells me you have a typo in the if/then statement. I think it should be $creditMemo->getAmcheckoutfeesAmount() instead of $creditMemo->getAmcheckoutfeesmount(). 

But again, it is hard to debug this as it is a custom edit and I'm not familiair with the used plugin, so I could be wrong.

**Comment by michael85a** [comment]
@Frank-Magmodules , thanks 
i'll come back to you
