### ISSUE TITLE
Mollie payments not showing up in the checkout

### ISSUE THREAD

**Issue by falconmedia** [mollie/Magento#152]
Since update to 5.2.2 the Mollie Payments aren't visible in the checkout anymore.

The logfiles show

```
2019-10-18T15:33:52+00:00 DEBUG (7): error: Mollie API key not set (live modus)
2019-10-18T15:33:52+00:00 DEBUG (7): error: Mollie set to live modus, but API key does not start with "live_"
```

In dashboard all the API keys are setup well for every shop.

**Comment by Frank-Magmodules** [comment]
Hi @falconmedia ,

Can you please double check the entered API keys in the admin as the error states it is not noticing an API key that start with the "live_". Maybe this was set on store-view or website level. Also try and flush the cache afterwards. If this does not solve the issue, please [sent](https://www.magmodules.eu/contact-us.html) us an admin login so we can take a look with you.

Frank
