### ISSUE TITLE
Fatal error after placing order

### ISSUE THREAD

**Issue by LucasMDL** [mollie/Magento#154]
After selecting an order status in test modus, the following error is showing.

Fatal error: Undefined class constant 'XML_PATH_LOG_ENABLED' in Mollie/Mpm/Model/Mollie.php on line 347

**Comment by Marvin-Magmodules** [comment]
Hi @LucasMDL, thank you for issue report. We have reproduced this issues on Magento versions lower than 1.9.2.x. and just released a new version that fixes the issue; see [v5.5.3](https://github.com/mollie/Magento/releases/tag/v5.5.3). We are closing this issue now but please feel free to reopen the issue if this still occurs.
