### ISSUE TITLE
iDEAL QR code is always requested from Mollie API

### ISSUE THREAD

**Issue by willemstuursma** [mollie/Magento#159]
The iDEAL QR code is always requested from Mollie API even though the setting is not enabled. 

Can you please only request iDEAL QR codes if they are actually going to be shown to the shopper. 

See here https://github.com/mollie/Magento/blob/e18353c6b536999e2d530e017b58511b7b7fe9ba/app/code/community/Mollie/Mpm/Model/Client/Payments.php#L108 where the QR code is included.

**Comment by Frank-Magmodules** [comment]
Hi @willemstuursma, removed the request for QR code in the latest version [v5.5.5](https://github.com/mollie/Magento/releases/tag/v5.5.5) as this option was also removed from the module.
