### ISSUE TITLE
Consider moving CSS inline

### ISSUE THREAD

**Issue by loekvangool** [mollie/Magento#162]
This module adds a CSS file to every single Magento page, while it's only used in a single place: https://github.com/mollie/Magento/search?q=.mollie-loading&unscoped_q=.mollie-loading

Please consider moving the CSS inline?

**Comment by Frank-Magmodules** [comment]
@loekvangool,  thank you  for opening this issue, I've sent this to our team as a potential improvement for the upcoming release!

**Comment by Marvin-Magmodules** [comment]
Hi @loekvangool, thanks again for opening this issue. The issue has been resolved in the [v5.5.6](https://github.com/mollie/Magento/releases/tag/v5.5.6), where the css has been moved to the correct layout handle. We are closing this issue now but please feel free to reopen the issue if this still occurs.
