### ISSUE TITLE
DEBUG (7): error: Missing Redirect Url

### ISSUE THREAD

**Issue by seansan** [mollie/Magento#165]
Hi, we just installed mollie and are seeing the occasional 

DEBUG (7): error: Missing Redirect Url

Problem is we dont know for which store? account? customer?

To fix/debug it would be good to have a little more info

**Comment by Marvin-Magmodules** [comment]
Hi @seansan thank you for opening the issue. We have just released the [v5.5.6](https://github.com/mollie/Magento/releases/tag/v5.5.6) release, where we have added the increment id to this log record. We are closing this issue now but please feel free to reopen the issue if this still occurs.
