### ISSUE TITLE
I get 2 fatal errors when trying to add product into cart

### ISSUE THREAD

**Issue by Aquive** [mollie/Magento#169]
Hi,

I get both below errors when trying to add a product in the cart. Magento version 1.9.2.2.

`Fatal error: Uncaught TypeError: Argument 1 passed to GuzzleHttp\Client::send() must be an instance of GuzzleHttp\Message\RequestInterface, instance of GuzzleHttp\Psr7\Request given, called in /data/web/public/lib/Mollie/Mollie/src/MollieApiClient.php on line 426 and defined in /data/web/public/lib/Ing/Services/ing-php/vendor/guzzlehttp/guzzle/src/Client.php on line 159`

`TypeError: Argument 1 passed to GuzzleHttp\Client::send() must be an instance of GuzzleHttp\Message\RequestInterface, instance of GuzzleHttp\Psr7\Request given, called in /data/web/public/lib/Mollie/Mollie/src/MollieApiClient.php on line 426 in /data/web/public/lib/Ing/Services/ing-php/vendor/guzzlehttp/guzzle/src/Client.php on line 159`

Any idea's how to solve this? I seems it might have to do something with the ING module. I am looking into the details right now.

Regards

**Comment by Frank-Magmodules** [comment]
Hi @Aquive ,

That looks like some dependencies are mixed up. The Mollie SDK requires Guzzle 6.3 or higher, the error indicates that you are using Guzzle ~5. 

Frank

**Comment by Aquive** [comment]
Hi Frank,

Thanks for your reply. Yes the ING Kassa extension seems to use an older version of Guzzle. Is it possible to force each extension to use their own version?

Regards,
Akif

**Comment by Frank-Magmodules** [comment]
HI @Aquive ,

We can't do a lot from the Mollie perspective but I recommend updating the ING extension as it seems [Guzzle is removed](https://github.com/ingpsp/magento/search?q=guzzle&unscoped_q=guzzle) on newer versions of the [ING PSP](https://github.com/ingpsp/magento/releases) extension. In case you already are using the latest version, then Guzzle is used somewhere else. Please try to update that extension as well.

Frank

**Comment by Frank-Magmodules** [comment]
Hi @Aquive ,

Any updates on this issue? 
Did the update of the ING module fix your issue?

Frank

**Comment by Aquive** [comment]
@Frank-Magmodules ,

I just disabled ING for now. We will review it later if we still need the extension. Thanks for getting back at me!

**Comment by Marvin-Magmodules** [comment]
Hi @Aquive, thanks for getting back on this! Closing this issue now, but feel free to reopen the issue if the problem still exists after updating the ING module.
