### ISSUE TITLE
Possible config quickwin: paymentmethod description setting fallback at global level

### ISSUE THREAD

**Issue by seansan** [mollie/Magento#171]
Would it be an idea / quickwin to add 1 global format for all payment methods? 

Something like {ordernumber} {storename} {paymentmethod} {customerName}

{paymentmethod} would then be inserted based on the current payment method

The Global description setting would then only be used if the specific (paymentmethod) field is empty

CURRENT

![image](https://user-images.githubusercontent.com/652395/80704457-de998100-8ae4-11ea-8e64-64e17e1f608a.png)

SUGGESTION

![image](https://user-images.githubusercontent.com/652395/80704546-143e6a00-8ae5-11ea-928d-d9080de90e2e.png)

**Comment by Frank-Magmodules** [comment]
Hi @seansan, Thank you for the feature request! 
As we don't see a big benefit of implementing this feature, we have decided to not implement this. 

Frank
