### ISSUE TITLE
Possible quick win for mollie ideal in checkout

### ISSUE THREAD

**Issue by seansan** [mollie/Magento#172]
Upon testing (and going back and forth in the checkout) we saw that when cancelling and retrying a payment that in the case of iDeal the choosen bank is forgotten and needs to be re-selected by the user

Flow
- Checkout, ideal, choose ING
- Cancel payment, cart, then checkout
- Ideal is selected, but ING bank not

Possible quick win could be to
- if user was recently here (case above) .. then also preselect the before chosen bank

And in addition for returning users, but with a new order
- if user is logged in and we have access to previous payment method and bank: then preselect this choice

Just an idea

![image](https://user-images.githubusercontent.com/652395/80704866-aba3bd00-8ae5-11ea-92e6-f678ca68efa6.png)

**Comment by Frank-Magmodules** [comment]
Hi @seansan, thank you for the feature request! 
This is a nice feature and we will add this to the backlog for the Magento 2 version.

However, we will not implement this in the Magento 1 module as the focus has shifted to Magento 2. We will keep supporting the Mollie M1 version (support & bug fixing), even after EOL of Magento 1 but we decided to not add this feature for now.
