### ISSUE TITLE
small string fold in admin row header fix

### ISSUE THREAD

**Issue by seansan** [mollie/Magento#174]
https://github.com/mollie/Magento/pull/173

After:
![image](https://user-images.githubusercontent.com/652395/80715078-2379e380-8af6-11ea-9367-4cbfad6ddb0d.png)

**Comment by Frank-Magmodules** [comment]
Hi @seansan ,

Thanks, we will implement this in the next release!

**Comment by Marvin-Magmodules** [comment]
@seansan. PR was has been merged into master and releases as [v5.5.7](https://github.com/mollie/Magento/releases/tag/v5.5.7). Thanks for the PR!
