### ISSUE TITLE
Quickwin? Add admin deeplink to payment in Mollie Environment

### ISSUE THREAD

**Issue by seansan** [mollie/Magento#175]
Quickwin? Add admin deeplink to payment in Mollie Environment

- Show payment id in admin customer order (when talking to Mollie)
- Place direct deeplink under it to the same payment in Mollie admin environment

Url would be something like this
https://www.mollie.com/dashboard/org_999999/payments/tr_rrJwd7uBRCpaymentid

Example

![image](https://user-images.githubusercontent.com/652395/80729982-4661c300-8b09-11ea-91c1-f9ab34415e01.png)

MOllie backend

![image](https://user-images.githubusercontent.com/652395/80730131-7a3ce880-8b09-11ea-9d9f-5ea42626621f.png)

**Comment by Frank-Magmodules** [comment]
Hi @seansan, thank you for the feature request! 
This is a nice feature and we will add this to the backlog for the Magento 2 version.

However, we will not implement this in the Magento 1 module as the focus has shifted to Magento 2. We will keep supporting the Mollie M1 version (support & bug fixing), even after EOL of Magento 1 but we decided to not add this feature for now.
