### ISSUE TITLE
On CC and iDEAL payment show card and bank issuer in sales order view

### ISSUE THREAD

**Issue by seansan** [mollie/Magento#176]
It is important to know which card the customer used, show this on order page

add method in block

    /**
     * @return string
     */
    public function getcardLabel()
    {
        try {
            $details = json_decode($this->getInfo()->getAdditionalInformation('details'));
            if ($details->cardLabel) {
                return $details->cardLabel;
            }
        } catch (\Exception $e) {
            $this->mollieHelper->addTolog('error', $e->getMessage());
        }
    }

Call method in phtml info block

<?php
/**
 * @see Mollie_Mpm_Block_Payment_Info_Paymentlink
 */
$status = $this->getPaymentStatus();
?>
    <div class="mollie-method">
        <p>
            <?php if ($img = $this->getPaymentImage()): ?>
                <img src="<?= $img ?>"/>
            <?php endif; ?>
            <?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
            <?php if (($cardlabel = $this->getcardLabel())): ?>
                (<?php echo $this->escapeHtml($cardlabel) ?>)
            <?php endif; ?>

**Comment by seansan** [comment]
Before

![image](https://user-images.githubusercontent.com/652395/80817683-33ff8c00-8bd2-11ea-8920-68496c2e5bad.png)


After

![image](https://user-images.githubusercontent.com/652395/80817656-277b3380-8bd2-11ea-9733-483c9aad6888.png)

**Comment by seansan** [comment]
Same may be possible for Ideal and bank name

**Comment by Frank-Magmodules** [comment]
Hi @seansan , thank you for opening this issue. The feature request has been added in the v[5.6.0](https://github.com/mollie/Magento/releases/tag/v5.6.0), where the used Creditcard issuer is now shown in the back-end. We are closing this issue now but please feel free to reopen the issue if this still occurs.
