### ISSUE TITLE
Missing Credit Card Components Javascript file in newest release.

### ISSUE THREAD

**Issue by dannyspijker** [mollie/Magento#183]
From version 5.6.0 the feature Mollie Components is added. But until the newest release the the javascript file is missing: Magento/skin/frontend/base/default/js/mollie/mpm/creditcard-components.js

**Comment by Frank-Magmodules** [comment]
Hi @dannyspijker, thank you for the issue report. It looks like the .JS file was missing in the ZIP file. 
We have updated the ZIP on the release page, a direct link to the new ZIP: https://github.com/mollie/Magento/releases/download/v5.6.1/mollie-magento-5.6.1.zip

**Comment by dannyspijker** [comment]
Hi @Frank-Magmodules, Awesome! I fixed the issue myself to get the javascript file directly from the source tagged with the latest release tag. But nice you have corrected the release zip. This will definitely help someone else.
