### ISSUE TITLE
Compatibility Issue Amasty One Step Checkout

### ISSUE THREAD

**Issue by mybinaryromance** [mollie/Magento#184]
When using Mollie (5.6.0) with Amasty One Step Checkout (3.2.10) on Magento CE  1.9.4.5 we notice quite a lot of pending orders in Magento with Mollie payments.
All these orders use Mollie Payments (Klarna and Sofort mainly but not only) and all of them miss the 'customer was redirected to Mollie' notice. We have no log entries about these orders (not in mollie.log, no exceptions, no php errors, no system log entries). By now we are also not able to reproduce the issue, it seems to show up randomly. If it shows up, customers get redirected to their shopping carts. The carts are not emptied, no error message is shown, customer quote data is still present. The order email is not send to the customer. If the customer re-attempts to checkout, it will mostly work after 2-4 attempts.
This error does not appear when using Mollie with core checkout. The error does also not appear with One Step Checkout and  non-Mollie Payments.

**Comment by Frank-Magmodules** [comment]
Hi @mybinaryromance ,

I know that there has been direct contact with you and Mollie about this issue but I'm not sure what the current state is of the issue. Can you please let me know if the issue still occurs or close the issue if it's not applicable anymore?
Also, feel free to [contact us directly](https://www.magmodules.eu/support-form.html).

Thank you!

**Comment by Frank-Magmodules** [comment]
Hi @mybinaryromance ,

Do you have any update on this issue?
Please let me know if you need any further assistance so we can help you out with this issue.

**Comment by mybinaryromance** [comment]
I drilled this one down to an issue with Amasty Onestep Checkout. They do not handle the onAjaxFailure method of magento checkout appropriately.

**Comment by robcodesign** [comment]
I'm sorry to bring up such an old issue again? But was there a solution. We have exactly the same problem here. We have Idev_OneStepCheckout in use and sometimes customers get directly from the checkout page to the start page... I can still see in the logs that /mpm/api/payment/ was called - as with all other orders, but these customers then land directly on the start page. 
I have also written additional logs - but I still don't know exactly where the error is occurring. 
We have the same issue, it's often Klarna as a payment method, but not only.

**Comment by mybinaryromance** [comment]
Hi @robcodesign,
in our case the error was caused by the onAjaxFailure method of the external checkout module. This method is (or should be) called whenever an exception is thrown during the POSTing of the order data. You might want to make sure that your checkout module logs exceptions that are thrown after submitting the checkout.
A common exception thrown by the mollie extension during the order creation process is the KlarnaException. This exception is thrown by design when the customer has a previous klarna order that has failed (klarna orders being klarna pay later, klarna sofort and klarna slice) and is trying to use klarna again.
