### ISSUE TITLE
Total Paid in order set twice with Klarna

### ISSUE THREAD

**Issue by mybinaryromance** [mollie/Magento#185]
When using Klarna Payment Methods (Pay later) in Magento CE 1.9.4.5 the order total paid amount is doubled. This is only in order view. The invoice is created correctly, and so are creditmemos.

mollie.log (this example order) contains these errors:
2020-07-15T08:27:03+00:00 DEBUG (7): error: Missing Redirect Url, increment ID: #M-100023937
2020-07-15T08:27:09+00:00 DEBUG (7): error: Missing Redirect Url, increment ID: #M-100023937

![mollie_overpay_db](https://user-images.githubusercontent.com/8794344/90106386-9e82a500-dd47-11ea-8f84-fdf425fe61da.png)
![mollie_overpay](https://user-images.githubusercontent.com/8794344/90106393-a3475900-dd47-11ea-9bd5-4d97cf09be83.png)

**Comment by Frank-Magmodules** [comment]
Hi @mybinaryromance ,

I know that there has been direct contact with you and Mollie about this issue but I'm not sure what the current state is of the issue. Can you please let me know if the issue still occurs or close the issue if it's not applicable anymore?
Also, feel free to [contact us directly](https://www.magmodules.eu/support-form.html).

Thank you!

**Comment by Frank-Magmodules** [comment]
Hi @mybinaryromance ,

Do you have any update on this issue?
Please let me know if you need any further assistance so we can help you out with this issue.

**Comment by mybinaryromance** [comment]
The issue is still occuring. As a workaround I am currently using a local overwrite of Mollie_Mpm_Model_Client_Orders where I added a check for $order->getTotalDue() before creating the invoice. this is around line 273 in Mollie_Mpm_Model_Client_Orders::processTransaction().

**Comment by Frank-Magmodules** [comment]
Hi @mybinaryromance,

We are happy to share that we've just released the new [5.6.3](https://github.com/mollie/Magento/releases/tag/v5.6.3) version with a fix for this issue. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
