### ISSUE TITLE
Can't send orders in Magento that are in pending Status

### ISSUE THREAD

**Issue by ayoubelhobbi** [mollie/Magento#186]
Hello, 

I can't send the orders that are in the status pending. That happens only since latest versions. Is there a way to prevent that? Some times people can't pay and the order is created. I send them a payment link. They pay and I can't send the order! 

Thanks 
Ayoub

**Comment by Frank-Magmodules** [comment]
HI @ayoubelhobbi ,

Thank you for opening this issue, as the OrderAPI uses the Mollie status flow shown below, it's not possible to ship the order when the payment is in a pending state. Are you sure that that the payment has the status _Paid_ or _Authorized_?
As that is status is required to ship the order.

![order-status-flow@2x](https://user-images.githubusercontent.com/24823946/91152333-1e512d80-e6bf-11ea-8f48-d58f35d7c68e.png)

**Comment by Frank-Magmodules** [comment]
HI @ayoubelhobbi , do you have an update on this, or do you still need help with anything? Let me know!

**Comment by Frank-Magmodules** [comment]
@ayoubelhobbi ,
Due to inactivity, we are closing this issue now but please feel free to reopen the issue if this still occurs.
