### ISSUE TITLE
Magento cookie same site support (Support "SameSite" cookie property)

### ISSUE THREAD

**Issue by seansan** [mollie/Magento#187]
There are some (urgent) issues being reported esp for PSP's with the new cookie properties

Read here:
https://github.com/OpenMage/magento-lts/issues/414#issuecomment-682160131

Is this / clould this be an issue for the MOLLIE extension?

**Comment by michielgerritsen** [comment]
Hi @seansan,

By default, the Mollie extension doesn't include any external javascript/resources. Only when the credit card components option is enabled there will be external javascript included so then it's relevant.

**Comment by Marvin-Magmodules** [comment]
Hi @seansan, closing this issue now as this is not something that needs to be fixed in the Mollie module.
