### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to GuzzleHttp\Client::send() must implement interface

### ISSUE THREAD

**Issue by rudracomputech** [mollie/Magento#188]
Hello I installed it on my Magento 1.9.4.0 but when we try to add product to cart we are getting bellow error
<pre>
Fatal error: Uncaught TypeError: Argument 1 passed to GuzzleHttp\Client::send() must implement interface GuzzleHttp\Message\RequestInterface,
instance of GuzzleHttp\Psr7\Request given, called in /lib/Mollie/Mollie/src/MollieApiClient.php on line 427 and defined in /lib/Ing/Services/ing-php/vendor/guzzlehttp/guzzle/src/Client.php:158
Stack trace: #0 /lib/Mollie/Mollie/src/MollieApiClient.php(427): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array) 
#1 /lib/Mollie/Mollie/src/MollieApiClient.php(384): Mollie\Api\MollieApiClient->performHttpCallToFullUrl('GET', 'https://api.mol...', NULL) 
#2 /lib/Mollie/Mollie/src/Endpoints/EndpointAbstract.php(150): Mollie\Api\MollieApiClient->performHttpCall('GET', 'methods?resourc...') #3 /lib/Mollie/Mollie/src/Endpoints/MethodEndpoint.php(63): Mollie\Api\Endpoints\EndpointAbstract->rest_list(NULL, NULL, Array) #4 /home/peak in /lib/Ing/Services/ing-php/vendor/guzzlehttp/guzzle/src/Client.php on line 158
</pre>

**Comment by Marvin-Magmodules** [comment]
Hi @rudracomputech, see issue: https://github.com/mollie/Magento/issues/169 for more information and a fix for this issue. Closing this issue now, but feel free to reopen it if the solution in https://github.com/mollie/Magento/issues/169 does not solve your issue.
