### ISSUE TITLE
Notice: Undefined property: stdClass::$cardLabel

### ISSUE THREAD

**Issue by HRR1337** [mollie/Magento#197]
Ik gebruik versie 5.6.3 en krijg deze melding in de Log.

Ik heb de cardlabels uitgezet in mijn config en gebruik OneStepCheckout (mocht dat relevant zijn).

Notice: Undefined property: stdClass::$cardLabel  in /home/xxx/domains/xxx/public_html/app/code/community/Mollie/Mpm/Block/Payment/Info/Base.php on line 153

**Comment by Frank-Magmodules** [comment]
Hi @HRR1337 ,

Thank you for opening the issue. We've created a fix that is going to be implemented in the upcoming release. Thank you for your contribution to this.

**Comment by Frank-Magmodules** [comment]
HI @HRR1337 ,

We are happy to share that we've just released the new [5.6.4](https://github.com/mollie/Magento/releases/tag/v5.6.4) version with a fix for this issue. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
