### ISSUE TITLE
iDEAL orders via Payments API not set to processing

### ISSUE THREAD

**Issue by mlaurense** [mollie/Magento#205]
We recently updated from 4.4.0 to 5.6.5, on a Magento 1.8.1.0 environment. After this update, we noticed orders not being set to 'processing' state. We changed over to Orders API, which seemed to fix it, but then some orders would still be placed using the Payments API, and would not be set to processing.

After debugging this issue, I found that the Orders API sets the state and then calls save() immediately:
https://github.com/mollie/Magento/blob/15bf1f5e94ba97278a8467ecc68a02e29e696dc3/app/code/community/Mollie/Mpm/Model/Client/Orders.php#L284

This is not the case with the Payments API:
https://github.com/mollie/Magento/blob/15bf1f5e94ba97278a8467ecc68a02e29e696dc3/app/code/community/Mollie/Mpm/Model/Client/Payments.php#L209

I added the call to the save function in the Payments API myself, which seems to fix this issue. I am not entirely sure this issue is caused by the Mollie extension, or some other extension which is conflicting here...

**Comment by Frank-Magmodules** [comment]
Hi @mlaurense ,

We are happy to share that we've just released the new [5.6.7](https://github.com/mollie/Magento/releases/tag/v5.6.7) version with a fix for your issue. Thank you for the detailed issue report on this issue, we are closing the issue now but please feel free to reopen the issue if this still occurs.

**Comment by Frank-Magmodules** [comment]
Hi @mlaurense ,

We are happy to share that we've just released the new [5.6.7](https://github.com/mollie/Magento/releases/tag/v5.6.7) version with a fix for your issue. Thank you for the detailed issue report on this issue, we are closing the issue now but please feel free to reopen the issue if this still occurs.
