### ISSUE TITLE
Missing transaction details

### ISSUE THREAD

**Issue by mlaurense** [mollie/Magento#206]
After migration from 4.x to 5.x the Transaction Details aren't shown in the Magento admin anymore. I see a setting in the Mollie Magento settings (Show Transaction Details), but it appears there isn't any template that uses this setting to show the actual details.

In 4.x, the details were rendered by this file:
https://github.com/mollie/Magento/blob/v4.5.4/app/design/adminhtml/default/default/template/mollie/mpm/payment/info.phtml
This file is not in the 5.x repo.

**Comment by Frank-Magmodules** [comment]
Hi @mlaurense ,

We are happy to share that we've just released the new [5.6.7](https://github.com/mollie/Magento/releases/tag/v5.6.7) version with a fix for your issue. We are closing this issue now but please feel free to reopen the issue if this still occurs.
