### ISSUE TITLE
Klarna Pay Later with status failed doesn't restore qty.

### ISSUE THREAD

**Issue by Martin-DAN** [mollie/Magento#210]
If payment with **Klarna Pay Later** returns status **failed** then the product **qty** is **not restored**.

Using Module Version:  **5.6.5**

**Comment by Frank-Magmodules** [comment]
Hi @Martin-DAN ,

  
We are happy to share that we've just released the new [5.6.8](https://github.com/mollie/Magento/releases/tag/v5.6.8) version with a fix for your issue. We are closing this issue now but please feel free to reopen the issue if this still occurs.
