### ISSUE TITLE
Request for quotation

### ISSUE THREAD

**Issue by aljoharahG** [mollie/Magento#215]
How can I code a page for "request for quotation" products in magento 1?

**Comment by Frank-Magmodules** [comment]
HI @aljoharahG , not sure how this is reflecting the Mollie Payment plugin, if you think it is we do need more details on this issue.

**Comment by jankovandeventer** [comment]
@aljoharahG https://www.cart2quote.com/

**Comment by Frank-Magmodules** [comment]
HI @aljoharahG , as this is not directly reflecting the Mollie Payments plugin, we are closing this issue.
