### ISSUE TITLE
Klarna Pay Now not availabe in Magento 1 Module

### ISSUE THREAD

**Issue by jankovandeventer** [mollie/Magento#217]
Feature request: add Klarna Pay Now

Klarna Pay Now is not available in the Magento module.
https://www.klarna.com/nl/zakelijk/producten/betaal-nu/

**Comment by Marvin-Magmodules** [comment]
Hi @jankovandeventer,

We are happy to share that we've just released the new [v5.8.0](https://github.com/mollie/Magento/releases/tag/v5.8.0) version where we have covered this feature request! Thank you for opening this issue and for the detailed feature request report. We are closing this issue now but please feel free to reopen the issue if this still occurs.
