### ISSUE TITLE
Incorrect Grand Total Calculation when different tax rate in different country

### ISSUE THREAD

**Issue by abcrkt** [mollie/Magento#227]
Hi

we have Magento store which deliver product in different country, so based on country different tax rate applied. for example when select Germany it should charge 19% but when select UK it should charge 0% tax. 

before installing Mollie extension all thing working fine but after install this extension it calculate tax properly but grand total not Recalculating.

Magento ver. 1.9.3.8

attached image when we select UK Tax: 0.00 (Correct) Subtotal(Correct), Grand Total Incl Tax and Grand Total Incl Tax(Incorrect)

<img width="865" alt="image" src="https://user-images.githubusercontent.com/6523521/215709403-51126b1e-a282-4150-8b00-2e8525a386c6.png">

Thanks

**Comment by Frank-Magmodules** [comment]
Hi There @abcrkt , Is this issue still relevant? If so, please provide more information on how to reproduce it in a clean Magento 1 environment so we can assist you further.

**Comment by Frank-Magmodules** [comment]
Due to inactivity, we are closing this issue for now. Feel free to reopen it whenever you need further assistance.
