### ISSUE TITLE
Set $_canUseInternal to false, because payment methods can't be used in the backend.

### ISSUE THREAD

**Issue by bramvanderholst** [mollie/Magento#23]
https://github.com/mollie/Magento/blob/master/app/code/community/Mollie/Mpm/Model/Api.php#L78

**Comment by ottonet** [comment]
Don't completely agree with this. Almost all methods could be used internally - especially if Mollie would expand on their Magento plugin and integrate their Payment Link (betaallink) service. I would love to be able to:

1) create an order in the admin
2) select mollie/betaallink as payment option
3) Have this link automatically sent to the customer once I created the order.

**Comment by Daanvm** [comment]
Thanks for your suggestions.

We are currently thinking about a major update for our Magento module and what new features we would like to add. I've added this issue to the list. We don't have a release date, but because of the other projects we're working on it'll probably take a few months.

**Comment by vicding** [comment]
Since this is 1 year ago, I am wondering if the payment link method is available in the current release of mollie-magento?

**Comment by mdehaan** [comment]
Why is this functionality still not developed 2 years later?? I'm considering consulting our customers to use other payment providers that do have this option.

**Comment by jorgb90** [comment]
We need this!!

**Comment by lukawefocus** [comment]
@Daanvm 5 years later, still no payment link option / internal payment method. Why is this taking so long?

**Comment by Marvin-Magmodules** [comment]
Hi @lukawefocus what version are you running on at this moment? The Payment Link method was added some years ago , see: https://github.com/mollie/Magento/commits/master/app/code/community/Mollie/Mpm/Model/Method/Paymentlink.php
