### ISSUE TITLE
Missing DB update for the order object if a transaction of the 'success' type is triggered(PaymentsAPI)

### ISSUE THREAD

**Issue by fedkaWue** [mollie/Magento#230]
It seems like the bug wasn't fix  by the commit https://github.com/mollie/Magento/commit/2bd440b5a55601e008a99c04c1d23a8cdffd65b3. We've still got the issue if the order object has to be saved to the DB. During a success transaction (not if a webhook was fired) the hasDataChanges flag of the object is not switched and therefore no DB update will be triggered.
(See also our repo comment https://github.com/mollie/Magento/commit/2bd440b5a55601e008a99c04c1d23a8cdffd65b3)

**Comment by Frank-Magmodules** [comment]
Hello, @fedkaWue ! Your patience is much appreciated. We are thrilled to inform you that we have recently launched an [updated version](https://github.com/mollie/Magento/issues) of the Magento 1 plugin, which addresses the problem you reported. As of now, I am closing this particular issue. However, if you encounter any further concerns, please feel free to reopen it. Thank you!
