### ISSUE TITLE
After installing this Extension the Cart Rule condition not working. base_subtotal is always by 0

### ISSUE THREAD

**Issue by primasysteme** [mollie/Magento#232]
For example  by Cart rule: I have a Condition "Subtotal  equals or greater than  500  " it is not working. I have debuged, the value base_subtotal is 0. If I deactivate the extension it works and base_subtotal is not 0.

Thanks
Usman

**Comment by Frank-Magmodules** [comment]
Hi There @primasysteme ,Is this issue still relevant? If so, please provide more information on how to reproduce it in a clean Magento 1 environment so we can assist you further.

**Comment by Frank-Magmodules** [comment]
Due to inactivity, we are closing this issue for now. Feel free to reopen it whenever you need further assistance.
