### ISSUE TITLE
Problems with VAT calculation for the shippingcost

### ISSUE THREAD

**Issue by AlterWeb** [mollie/Magento#238]
Your support team asked me to create a issue over here with this problem (support ticket 1793653). 

The calculation of the shipping cost is of since we installed the latest version of your module. With your module enabled it now shows €23.34 (the incorrect amount, it looks like the VAT is added double):

![Schermafdruk van 2023-08-15 11-35-57](https://github.com/mollie/Magento/assets/12827587/b73fb93c-588b-4e30-a858-b42980b096e8)

And with it disabled €20,00 (the correct amount as we set it to €20 including vat):

![Schermafdruk van 2023-08-15 11-35-02](https://github.com/mollie/Magento/assets/12827587/0207b52a-3db7-4dc7-bfd2-c62069dac8e2)

When I comment out the following lines in your module etc/config.xml file the problem disappears, but I'm not sure that this won't cause other problems:

![Schermafdruk van 2023-08-15 12-09-31](https://github.com/mollie/Magento/assets/12827587/7e08a8f9-a677-44da-aa56-414ebbe89ccf)

**Comment by AlterWeb** [comment]
Hello @Frank-Magmodules, thank you for your response. I already provided the Mollie support with access to the frontend and backend of our staging environment by mail. For security reasons I can not provide the credentials over here, so please get them from our mail to Mollie. If you also need SSH access to debug this problem I need your SSH key. For security reasons the SSH key also has to be provided by a Mollie employee in reply on the previous mentioned ticket.

**Comment by Frank-Magmodules** [comment]
Hello @AlterWeb, we have received the information and can now begin investigating your issue. Thank you for your patience.

**Comment by AlterWeb** [comment]
Hi @Frank-Magmodules , thank you for your previous update. Do you have any news on this issue?

**Comment by Frank-Magmodules** [comment]
Hello @AlterWeb, I've just sent you an email containing an update. Thank you for your patience.

**Comment by AlterWeb** [comment]
@Frank-Magmodules unfortunately I didn't get any email. I did check my spam folder.

**Comment by Frank-Magmodules** [comment]
We're closing this matter as it stems from a conflict within the Cardgate_Cgp.xml plugin.
