### ISSUE TITLE
No title for Mollie Payment Methods

### ISSUE THREAD

**Issue by ottonet** [mollie/Magento#24]
In Magento it is common practice to have a title available for the separate payment methods. See this excerpt from core_config_data: 

~~~
1318	default	0	payment/paypal_standard/title	Paypal (Visa, Mastercard, American Express)
1333	default	0	payment/paypal_express/title	PayPal Express Checkout
1348	default	0	payment/paypal_billing_agreement/title	PayPal Billing Agreement
1371	default	0	payment/ccsave/title	Credit Card (saved)
1381	default	0	payment/banktransfer/title	Vooruitbetaling
1389	default	0	payment/checkmo/title	Check / Money order
1398	default	0	payment/cashondelivery/title	Levering onder rembours
1405	default	0	payment/free/title	No Payment Information Required
1411	default	0	payment/purchaseorder/title	Purchase Order
1419	default	0	payment/authorizenet_directpost/title	Credit Card Direct Post (Authorize.net)
1437	default	0	payment/authorizenet/title	Credit Card (Authorize.net)
1457	default	0	payment/bitmerchant/title	Bitcoin via BitMerchant
2369	stores	5	payment/banktransfer/title	Bank Transfer
~~~

Many third party extensions rely on this information. In our case, the connector for our warehouse requires the title to be set: 

~~~
    /**
     * Get all the active payment methods
     * 
     * @return array
     */
    public function getActivPaymentMethods()
    {
        $payments = Mage::getSingleton('payment/config')->getActiveMethods();

        $methods = array();
        foreach ($payments as $paymentCode=>$paymentModel) {
            $paymentTitle = Mage::getStoreConfig('payment/'.$paymentCode.'/title');
            $methods[$paymentCode] = array(
                'label'   => $paymentTitle,
                'value' => $paymentCode,
            );
        }
        return $methods;
    }     
~~~

Mollie/Magento however does not offer support for these titles, either "auto-generated" or the more common solution of allowing the administrator to edit these titles through the backend config settings. 

In our case the workaround is easy. We have added the following to core_config_data by hand: 

~~~
path                          title
payment/mpm_void_01/title     Mollie Method 01
payment/mpm_void_02/title     Mollie Method 02
payment/mpm_void_03/title     Mollie Method 03
etc. etc. 
~~~

While this issue is not urgent at all, I do want to suggest that the Mollie/Magento plugin should follow standard Magento practices to ensure maximum compatibility _out of the box_ with other 3rd party extensions.

**Comment by ottonet** [comment]
Adding to this issue, our bookkeeping would like to see the real payment method name instead of "mpm_void_00" or "mpm_void_01" in Magento Admin interface. This makes it a lot easier to match payments with orders. 

See: 
![screen shot 2015-05-04 at 14 12 08](https://cloud.githubusercontent.com/assets/6705804/7453314/26fb845e-f268-11e4-9cb3-5a099452968e.png)

**Comment by iamniels** [comment]
> I do want to suggest that the Mollie/Magento plugin should follow standard Magento practices to ensure maximum compatibility out of the box with other 3rd party extensions.

I agree. I understand the logic behind the current solution, but for stores with many extensions it complicates integration a lot.

**Comment by janw-oostendorp** [comment]
We also have this problem as we like to mix this up per storeview.  
The payment names underwater is also annoying because we also use it in admin parts.

I did found some stuff in the `mollie_methods` table. But nothing that really helps.

**Comment by Daanvm** [comment]
Thanks for creating this issue.

We are currently thinking about a major update for our Magento module and what new features we would like to add. I've added this issue to the list. We don't have a release date, but because of the other projects we're working on it'll probably take a few months.

**Comment by mollierobbert** [comment]
We currently still don't have a Magento 2 module, sadly (see Adriaan's comment at https://github.com/mollie/Magento/issues/42). It would fix this issue for anyone who can upgrade to Magento 2. Please follow issue #42 for updates on the Magento 2 release.

For Magento 1, we don't have the resources to fix this semantic issue. The payment methods are working fine as they are, even though they don't appear in the admin panel as one would expect.

I'm marking this issue as a WONTFIX. But feel free to open a pull request if this is urgent enough for you to fix it.
