### ISSUE TITLE
Issue with PHP 8.2

### ISSUE THREAD

**Issue by denzity86** [mollie/Magento#240]
Hi,

When I update the module to the latest version with PHP 8.2, when I login to the admin I see an error 404 (Not found).

Seems this is causing the issue:
https://github.com/mollie/Magento/blob/master/app/code/community/Mollie/Mpm/etc/adminhtml.xml#L35

When the **module= "mpm"** is in the code, it's not working.. but when I remove it, the translation won't work.
Same goes for the <children> items

Can you maybe look into this?

Kind regards,
Dennis

**EDIT: Translations seem to work when i leave the module="mpm" out**

**Comment by Frank-Magmodules** [comment]
Hi There @denzity86 ,
Thank you for opening this issue. We’re pleased to inform you that we have recently released a [new version](https://github.com/mollie/Magento/releases/tag/v5.9.0) of the Magento 1 plugin that addresses the issue you described. I’m closing this issue for now, but feel free to respond or reopen it if needed.​
