### ISSUE TITLE
Helper_Data#isModuleEnabled crashes the adminhtml

### ISSUE THREAD

**Issue by Hanmac** [mollie/Magento#241]
https://github.com/mollie/Magento/blob/e3e85896d98aa362fd349841f160722a23e6a3de/app/code/community/Mollie/Mpm/Helper/Data.php#L85-L96

crashes the adminhtml, see this Stacktrace:

```
Mage_Core_Model_Store_Exception in /var/www/bauma1.9.x/app/code/core/Mage/Core/Model/App.php:1484
Stack trace:
#0 /var/www/app/code/core/Mage/Core/Model/App.php(882): Mage_Core_Model_App->throwStoreException()
#1 /var/www/app/Mage.php(411): Mage_Core_Model_App->getStore('Mollie_Mpm')
#2 /var/www/vendor/mollie/magento/app/code/community/Mollie/Mpm/Helper/Data.php(132): Mage::getStoreConfig('payment/mollie/...', 'Mollie_Mpm')
#3 /var/www/vendor/mollie/magento/app/code/community/Mollie/Mpm/Helper/Data.php(107): Mollie_Mpm_Helper_Data->getStoreConfig('payment/mollie/...', 'Mollie_Mpm')
#4 /var/www/vendor/mollie/magento/app/code/community/Mollie/Mpm/Helper/Data.php(95): Mollie_Mpm_Helper_Data->isAvailable('Mollie_Mpm')
#5 /var/www/app/code/core/Mage/Core/Helper/Abstract.php(134): Mollie_Mpm_Helper_Data->isModuleEnabled('Mollie_Mpm')
#6 /var/www/app/code/core/Mage/Adminhtml/Block/Page/Menu.php(307): Mage_Core_Helper_Abstract->isModuleOutputEnabled()
#7 /var/www/app/code/core/Mage/Adminhtml/Block/Page/Menu.php(127): Mage_Adminhtml_Block_Page_Menu->_isEnabledModuleOutput(Object(Varien_Simplexml_Element))
#8 /var/www/app/code/core/Mage/Adminhtml/Block/Page/Menu.php(88): Mage_Adminhtml_Block_Page_Menu->_buildMenuArray(Object(Varien_Simplexml_Element))

```

Because the Adminhtml refers to mpm: `<mollie module="mpm">`, the Menu class is looking if the Module is Enabled or not

The Original Method uses `$moduleName` and not `$storeId = null`

```php
public function isModuleEnabled($moduleName = null)
```

**Comment by Frank-Magmodules** [comment]
Thank you for opening this issue @Hanmac . We’re pleased to inform you that we have recently released a [new version](https://github.com/mollie/Magento/releases/tag/v5.9.0) of the Magento 1 plugin that addresses the issue you described. We will also close the related PR, but we want to express our gratitude for your effort in sharing this issue and fix with us. I’m closing this issue for now, but feel free to respond or reopen it if needed.​

**Comment by Hanmac** [comment]
I wouldn't call it fixed, more like patched

maybe in a next major, the `deprecated` function can be removed, and the whole problem can be avoided

(issue doesn't need to be reopened)

**Comment by Frank-Magmodules** [comment]
Hi There @Hanmac ,

Thank you for your response. This function is indeed marked as `deprecated` and may need to be removed. However, this extension is currently in maintenance mode. This means that we will fix any bugs that arise, but we won’t add new features unless absolutely necessary. Thank you for your understanding!
