### ISSUE TITLE
Customers Not Redirected to Mollie After Checkout

### ISSUE THREAD

**Issue by robcodesign** [mollie/Magento#243]
I'm sorry to bring up such an old issue again. We are experiencing a problem where some customers are not being redirected to Mollie. We are using Idev_OneStepCheckout, and occasionally, customers are taken directly from the checkout page to the start page after pressing the order button. According to the access logs, the endpoint /mpm/api/payment/ is being called as with all other orders, but these customers then land directly on the start page. The order is created in magento but does not appear in the Mollie dashboard.

I have added additional logging, but I still cannot pinpoint where the error is occurring. This issue often involves Klarna as a payment method, but it is not exclusive to Klarna.

**Comment by Frank-Magmodules** [comment]
Hi there @robcodesign, it's hard to determine what's going wrong based on this information. However, I'm happy to take a look with you. Could you please contact us [directly](https://www.magmodules.eu/help#:~:text=products%20and%20services.-,Support%20by%20e%2Dmail,-contact%40magmodules.eu) so we can investigate it together?

**Comment by Frank-Magmodules** [comment]
Hi There @robcodesign , We haven’t received any updates on this issue. Is it still relevant, or can we close it? Thank you!

**Comment by Frank-Magmodules** [comment]
Due to inactivity, we are closing this issue for now. Feel free to reopen it whenever you need further assistance.
