### ISSUE TITLE
Unable to configure sort order

### ISSUE THREAD

**Issue by iamniels** [mollie/Magento#25]
There are no options to configure the sort order of payment methods. We mix Mollie payment methods with the methods from other payment providers, therefore sorting is essential.

I tested with release 4.1.9

**Comment by janw-oostendorp** [comment]
This is indeed a problem. We have the issue because we want to sort the payment orders per storeview. Which also isn't possible.

**Comment by Daanvm** [comment]
The order of the payment methods is determined based on the current locale of the consumer. For dutch consumers iDEAL will be on top, for german consumers it's Sofort, etc. It is not possible to change the order yourself.

**Comment by janw-oostendorp** [comment]
@Daanvm Please fix this in the major update you mentioned in an other issue. It's a very standard thing.

**Comment by Daanvm** [comment]
@janw-oostendorp I've added it to our todo list!

**Comment by mollierobbert** [comment]
We won't fix this for Magento 1. the Magento 2 release will include the functionality.
