### ISSUE TITLE
Customer is forwarded to onepage/success after cancelled credit card payment

### ISSUE THREAD

**Issue by iamniels** [mollie/Magento#26]
Tested with release 4.1.9 and live API key. Magento 1.8.1

Place order -> select Mollie credit card -> Submit order

On Mollie credit card form, choose "Go back to website" -> results in /onepage/success and sends order confirmation.

Expected result: Forward to cart with message "payment failed"

**Comment by Daanvm** [comment]
Thanks for your message. We received your e-mail to support@mollie.com and you can expect a reply soon.
