### ISSUE TITLE
Order succes when canceling payment.

### ISSUE THREAD

**Issue by Jeordy** [mollie/Magento#28]
Version Magento 1.9.1.1.
When canceling a payment with Mollie iDeal, the order still gets accepted. The customer also gets an order confirmation.

Looks to me the order has to be canceled or set to "Pending Payment"?

**Comment by lvgunst** [comment]
Could you please send me your Mollie partner id and details about the order and payment to info@mollie.com? We will help you find the problem.

**Comment by Jeordy** [comment]
Dear Lennard,

We've solved the problem. There was a DNS-problem, that caused some problems accepting the Mollie return status. Sorry for the somewhat panicy issue and thank you for reacting so quickly.

Regards.
