### ISSUE TITLE
Order Success when cancelled

### ISSUE THREAD

**Issue by TimVroom** [mollie/Magento#31]
Even though this issue came up several times in other requests, we still experience the issue. especially when using a test env its given this response. Is it possible that the customer returns to the store before the order status is updated. We had to do a manual call to the api when the updated_status == empty.

In my opinion its possible that the customer returns to the store, before the update is send to magento (through the webhook). So in my opinion its still an issue that should be solved, either by checking the mollie api when this status is not set, or some other solution.

My main concern is: when the webhook isn't triggerd, the customer will still get the order confirmed even though the customer didn't pay.

**Comment by TimVroom** [comment]
No info? Well thats unfortunate..

**Comment by vincemore** [comment]
We experience the same problem.  And is causing a bit extra work.

**Comment by RicardoJ** [comment]
Thanks for creating this issue.

We are currently working on a major update for our Magento module. I've added this issue to the list. Unfortunately, we don't have a release date yet.

Ricardo,
Mollie.

**Comment by JBleijenberg** [comment]
@RicardoJ then why are you closing issues that clearly aren't fixed yet? I'm experiencing the same problem, 22 days later.

**Comment by tdgroot** [comment]
What's the status on this issue?
