### ISSUE TITLE
Magento 2 support

### ISSUE THREAD

**Issue by bkeetman** [mollie/Magento#33]
Seems there is no Magento 2 support yet for this module. Are there any plans to add this?

(Sorry, not really a bug.. more a feature)

**Comment by RicardoJ** [comment]
Hello Brain,

Currently we are making a new rewritten module for Magento 2. The release date is yet unknown but we will keep everybody up to date on our blog when the module has been released.

Ricardo,
Mollie

**Comment by Newllander** [comment]
Is there any estimation of the release date known for the M2 Mollie extension? I very much need it!

**Comment by RicardoJ** [comment]
Hello Newllander,

The estimated release date for version 2 is in Q1 of 2016. For more information, look at our [blog post](https://www.mollie.com/nl/blog/post/betaalmodules-van-mollie-voor-webshops-december-2015/) regarding our webshop modules (dutch content).

Ricardo,
Mollie

**Comment by Frits1980** [comment]
Is there a codebase on github yet to help develop?

**Comment by RicardoJ** [comment]
@Frits1980: I am in the process of doing that in my free time. Feel free to work aside me if you like. The repository is at: https://github.com/RicardoJ/mollie-magento2. If you like I can add you as a collaborator. I'll push my (so far) changes tomorrow in this repository.
