### ISSUE TITLE
Werkt dit nog?

### ISSUE THREAD

**Issue by LourensThalen** [mollie/Magento#36]
Heb het stappenplan gevolgd maar krijg behalve een titeltje "Payment Options" verder niets te zien (ook niet na uit- en opnieuw inloggen). Wordt deze plugin nog ondersteund?

Ik gebruik Magento 1.9.2.4

**Comment by RicardoJ** [comment]
Komt er iets voor in de exception logs of in de reports van Magento? Je kunt anders even het beste contact opnemen met info@mollie.com waar we je direct te woord kunnen staan m.b.t. dit issue.

**Comment by JBleijenberg** [comment]
Geen idee wat je onder werken verstaat.
Deze module houdt zich aan alles behalve de Magento/PSR2 standaard.
Rechtstreeks queries uitvoeren op de database. Funtiealiassen gebruiken waar dat helemaal niet nodig is. (sizeof() gebruiken ipv count() geeft mij de indruk dat deze module door een junior geschreven is).

Bij een geannulleerde betaling probeert hij een order status op te halen die geen updated_at waarde heeft waardoor de order goedgekeurd wordt..

**Comment by LourensThalen** [comment]
Ha Jeroen, dankjewel, maar deze was allang gesloten. Kan 'm niet verwijderen ;)
