### ISSUE TITLE
Same problem as multiple users - When cancelling the payment the order is set to success

### ISSUE THREAD

**Issue by mag-extension** [mollie/Magento#38]
Same problem as multiple users - When cancelling the payment the order is set to success.
For example, I choose Ideal as payment method, I go to the ideal screeen, I cancel the payment and it goes to the magento success page and the order is set to processing.

running the latest version of mollie with magento .1.9.0.1

**Comment by ndijkstra** [comment]
Hi! Sorry for the late response. Do you still have the problem with the plugin?
