### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by hans2103** [mollie/Magento#40]
Today I've installed Mollie using modman
According to Magento backend and supported by var/log/system.log there are some files missing.

<img width="390" alt="schermafdruk 2016-06-07 17 53 15" src="https://cloud.githubusercontent.com/assets/639822/15864805/c8dad0b2-2cd8-11e6-94e2-0830eb1e07b3.png">

They are removed with your commit https://github.com/mollie/Magento/commit/0cbb43852371766bc28d76f00ba9dab637b5e20f 

How can the issue be solved?

**Comment by RicardoJ** [comment]
The latest release is `v4.2.2` and is production ready. It can be downloaded from [here](https://github.com/mollie/Magento/releases/tag/v4.2.2). The master branch is a branch where unfinished changes are made.

I hope this helps.

Ricardo,
Mollie
