### ISSUE TITLE
Is there any version for PHP 5.3?

### ISSUE THREAD

**Issue by fancenl** [mollie/Magento#41]
Hi there!

One of my clients would like to use Mollie for his Magento-webshop. However, his server is still running PHP 5.3 and there is no quick way to upgrade to the newest 5.x in this situation. Can I use an older branch or something? The new way of defining arrays is not supported in 5.3 (the brackets [ and ]) and this will let the plugin crash.

Looking forward for an answer! :)

Jeffrey

**Comment by jurbr-entrust** [comment]
One of our clients also installed the latest Mollie module (4.2.3), with PHP 5.3 installed, and we're having problems also. Version 4.2.2 seems to be working though...

**Comment by RickWong** [comment]
Hi. We have no more plans to be backwards-compatible with unsupported PHP versions. A friendly yet serious reminder that it's a security risk to use any PHP version below 5.5, and soon 5.5 will also be EOL.

For more information see: http://php.net/supported-versions.php
