### ISSUE TITLE
Magento 2 support

### ISSUE THREAD

**Issue by ErikvdVen** [mollie/Magento#42]
Will there be support for Magento 2 any time soon? Cause there is a plugin for Magento 2 (http://www.ideal-module.com/nl/producten/magento2/mollie_extension_for_magento_2) which is paid AND doesn't support PHP 7 -_- . 

During installation (of that paid module) it complains it needs an ioncube loader for PHP 7.0 and after installing that version it complains it's written with ioncube 5.x which cannot be read with ioncube reader 7...

So if there will be support for Magento 2 for this module, it would be great. If I can be of any help with that, I'd love to help during my free time. The sooner I can launch my Magento 2 webshop, the better :)

**Comment by HRR1337** [comment]
Also very interested!

**Comment by adriaanmol** [comment]
Thanks for your interest.

As far as I know Magento 2 still hasn't a proper definition what the best implementation is of a payment gateway. That's one of the reasons why we waited so far. We're not very proud of our Magento 1.x-module so we want to build a new one from scratch for 2.x.

Meanwhile, you could check out [this implementation](http://www.appmerce.nl/mollie-ideal-magento.html#.V6BbemUTVGI). Also not free by the way and not support by Mollie.

Currently we also started to look for partners to develop our Magento 2.x-module. Whatever road we choose, we want to deliver a high quality implementation as fast as possible. It has priority here so hope it wont take to long.

**Comment by unreal4u** [comment]
Hi! Any news on this? Just implemented a new site with Magento 2 and realized this extension is not supported yet :(

Greetings.

**Comment by mollierobbert** [comment]
No news yet. An earlier attempt to develop the module with a partner failed. We're sorry for the delays.

**Comment by hansvanl** [comment]
Would love support for Magento 2 too! Planning to launch a Magento shop this year.

**Comment by Ylmzef** [comment]
Waiting for it!

**Comment by adriaanmol** [comment]
OK, we're busy building one right now together with a partner. More news hopefully in two weeks.

**Comment by rvdh** [comment]
Hi @adriaanmol - any update yet? :)

**Comment by yavuzaydin** [comment]
Are there any updates yet?

**Comment by adriaanmol** [comment]
The plugin is in review. Should not take long anymore.

**Comment by Grietzz** [comment]
That sounds good! Any idea how long this approximately will take?

**Comment by adriaanmol** [comment]
Sorry for keeping you guys waiting so long (quality before quantity). 😄 
We're planning a soft launch this Monday.

**Comment by ThomasVaRo** [comment]
Is the soft launch from Monday also compatible for the new Magento 2.1.3?

**Comment by robin-mollie** [comment]
@ThomasVaRo It most certainly is 🙂

**Comment by ThomasVaRo** [comment]
will it release soon? i kinda need to implement mollie in my magento xD

**Comment by adriaanmol** [comment]
Yes. It will!

**Comment by adriaanmol** [comment]
There we are! [Mollie Payments for Magento 2 beta](https://github.com/mollie/Magento2) is public.

Please be aware that this is a beta version and not advised to run on production yet. Installation only works with composer. In future releases we'll fix that.

**Comment by Grietzz** [comment]
When is it possible to use this in a live shop? It's the only thing missing in my shop. :)

**Comment by adriaanmol** [comment]
Hi @Grietzz.

You may use it for you live webshop if it feels OK for you. We've tested the plugin, but it's not battle tested through.
