### ISSUE TITLE
Connection timeouts cause unhandled exceptions

### ISSUE THREAD

**Issue by unxsist** [mollie/Magento#44]
When the Mollie API is not available/reachable due to network/downtime related issues. The Magento checkout crashes. It prevents the customer from checking out if other payment methods/providers are available.

Error Message: 

`Unable to communicate with Mollie (28): Connection timed out after 10001 milliseconds.`

Stacktrace:

`#0 /var/domains/***.nl/public_html/lib/Mollie/src/Mollie/API/Resource/Base.php(258): Mollie_API_Client->performHttpCall()
#1 /var/domains/***.nl/public_html/lib/Mollie/src/Mollie/API/Resource/Base.php(149): Mollie_API_Resource_Base->performApiCall()
#2 /var/domains/***.nl/public_html/lib/Mollie/src/Mollie/API/Resource/Base.php(243): Mollie_API_Resource_Base->rest_list()
#3 /var/domains/***.nl/public_html/app/design/frontend/base/default/template/mollie/form/details.phtml(8): Mollie_API_Resource_Base->all()`

**Comment by willemstuursma** [comment]
Thanks @unxsist! If you have the time to wrap up a quick pull request, that'd be great and else we'll look into it.
