### ISSUE TITLE
Blanc screen after uploading APP and LIB

### ISSUE THREAD

**Issue by crow73** [mollie/Magento#47]
Àfter uploading the mollie-magento-4.2.5 and flushing the cache i get a white screen in my back-end.
Only the upper row is vissable (with the logout button) nothing else.
![mollie-fail](https://cloud.githubusercontent.com/assets/16595094/19832456/4e60d666-9e24-11e6-9489-3336c48f62fe.jpg)

**Comment by ndijkstra** [comment]
Hi!

Can you verify that all files have been transferred to your server?

**Comment by crow73** [comment]
Yes my FTP programm don't give any errors and i removed every file by hand so i'm quite shure about that.
All the files in app and lib (not the files changelog.mdown, LICENSE, modman, readme.mdown and upgrading.mdown in the mollie-magento-4.2.5 map

**Comment by ndijkstra** [comment]
Can you create an admin and FTP account for us? You can send it to [info@mollie.com](mailto:info@mollie.com?subject=Nick Dijkstra) with my name as subject.

**Comment by ndijkstra** [comment]
Problem solved. Disabled compilation, installed the plugin and enabled the compilation.
