### ISSUE TITLE
Error for v 4.2.5 on Magento 1.9.3.1

### ISSUE THREAD

**Issue by puregraphx** [mollie/Magento#48]
We have just updated to Magento 1.9.3.1. and now we can no longer open the Payment Methods in the admin, nor the Mollie Settings in the main navigation in the admin. We always get an error report.

`a:5:{i:0;s:33:"String could not be parsed as XML";i:1;s:6224:"#0 /home/lalemans/public_html/app/code/community/Mollie/Mpm/Helper/Data.php(357): SimpleXMLElement->__construct('')
#1 /home/lalemans/public_html/app/design/adminhtml/default/default/template/mollie/system/config/status.phtml(62): Mollie_Mpm_Helper_Data->_getUpdateMessage()
#2 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/lalemans/...')
#3 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#4 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#5 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#6 /home/lalemans/public_html/app/code/community/Mollie/Mpm/Block/Adminhtml/System/Config/Status.php(53): Mage_Core_Block_Abstract->toHtml()
#7 /home/lalemans/public_html/lib/Varien/Data/Form/Element/Abstract.php(223): Mollie_Mpm_Block_Adminhtml_System_Config_Status->render(Object(Varien_Data_Form_Element_Text))
#8 /home/lalemans/public_html/lib/Varien/Data/Form/Element/Text.php(46): Varien_Data_Form_Element_Abstract->getHtml()
#9 /home/lalemans/public_html/lib/Varien/Data/Form/Element/Abstract.php(233): Varien_Data_Form_Element_Text->getHtml()
#10 /home/lalemans/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form/Fieldset.php(52): Varien_Data_Form_Element_Abstract->toHtml()
#11 /home/lalemans/public_html/lib/Varien/Data/Form/Element/Abstract.php(223): Mage_Adminhtml_Block_System_Config_Form_Fieldset->render(Object(Varien_Data_Form_Element_Fieldset))
#12 /home/lalemans/public_html/lib/Varien/Data/Form/Element/Abstract.php(233): Varien_Data_Form_Element_Abstract->getHtml()
#13 /home/lalemans/public_html/lib/Varien/Data/Form.php(244): Varien_Data_Form_Element_Abstract->toHtml()
#14 /home/lalemans/public_html/lib/Varien/Data/Form.php(256): Varien_Data_Form->toHtml()
#15 /home/lalemans/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(108): Varien_Data_Form->getHtml()
#16 /home/lalemans/public_html/app/design/adminhtml/default/default/template/widget/form.phtml(28): Mage_Adminhtml_Block_Widget_Form->getFormHtml()
#17 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/lalemans/...')
#18 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#19 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#20 /home/lalemans/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#21 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#22 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#23 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('form', true)
#24 /home/lalemans/public_html/app/design/adminhtml/default/default/template/system/config/edit.phtml(49): Mage_Core_Block_Abstract->getChildHtml('form')
#25 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/lalemans/...')
#26 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#27 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#28 /home/lalemans/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#29 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#30 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#31 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Text_List->_toHtml()
#32 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#33 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#34 /home/lalemans/public_html/app/design/adminhtml/default/default/template/page.phtml(67): Mage_Core_Block_Abstract->getChildHtml('content')
#35 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/lalemans/...')
#36 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#37 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#38 /home/lalemans/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#39 /home/lalemans/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#40 /home/lalemans/public_html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#41 /home/lalemans/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#42 /home/lalemans/public_html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(119): Mage_Core_Controller_Varien_Action->renderLayout()
#43 /home/lalemans/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#44 /home/lalemans/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#45 /home/lalemans/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#46 /home/lalemans/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#47 /home/lalemans/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#48 /home/lalemans/public_html/index.php(83): Mage::run('', 'store')
#49 {main}";s:3:"url";s:98:"/index.php/admin/admin568/system_config/edit/section/payment/key/8de410980a7862563a0b07c56d75c7e2/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}`

PS. the Module still seems to work on the frontend, it's the backend that always throws errors.

**Comment by PravindraSingh** [comment]
Having a similar issue on Magento 1.9.3.1. built on Centos 7 with php 5.6  Only the title for "Payment Methods" is appearing on fresh install. Rest of the configuration tabs are working. Is this permissions or a security key issue? 
![magent1 9](https://cloud.githubusercontent.com/assets/25531633/22617106/ffe1c67e-eac4-11e6-9db2-e444ef1eae74.jpg)

**Comment by ndijkstra** [comment]
Hi! This problem occurs when the Mollie lib is missing. Did you download the plugin from the releases page?

**Comment by germaike** [comment]
@ndijkstra 
i download it from the github download link and got a zip file with the master branch. Afterwards i uploaded the files with ftp and then got these errors / problems. Is there another way of installing this extension?

**Comment by ndijkstra** [comment]
You have to download the latests release from our releases page: https://github.com/mollie/Magento/releases. In this release the Mollie library is included.

**Comment by germaike** [comment]
@ndijkstra 
This release is working, thank you for the solution
