### ISSUE TITLE
Magento Giving 503 Error

### ISSUE THREAD

**Issue by deniozer** [mollie/Magento#57]
a:5:{i:0;s:1362:"SELECT `e`.`entity_id`, `e`.`type_id`, `e`.`attribute_set_id`, `e`.`name`, `e`.`price`, `e`.`small_image`, `e`.`short_description`, `e`.`news_from_date`, `e`.`news_to_date`, `e`.`special_price`, `e`.`status`, `e`.`entity_id`, `e`.`attribute_set_id`, `e`.`type_id`, `e`.`cost`, `e`.`created_at`, `e`.`gift_message_available`, `e`.`has_options`, `e`.`image_label`, `e`.`is_recurring`, `e`.`links_exist`, `e`.`links_purchased_separately`, `e`.`links_title`, `e`.`msrp`, `e`.`msrp_display_actual_price_type`, `e`.`msrp_enabled`, `e`.`name`, `e`.`news_from_date`, `e`.`news_to_date`, `e`.`price`, `e`.`price_type`, `e`.`price_view`, `e`.`recurring_profile`, `e`.`required_options`, `e`.`shipment_type`, `e`.`short_description`, `e`.`sku`, `e`.`sku_type`, `e`.`small_image`, `e`.`small_image_label`, `e`.`special_from_date`, `e`.`special_price`, `e`.`special_to_date`, `e`.`status`, `e`.`tax_class_id`, `e`.`thumbnail`, `e`.`thumbnail_label`, `e`.`updated_at`, `e`.`url_key`, `e`.`url_path`, `e`.`visibility`, `e`.`weight`, `e`.`weight_type`, `e`.`color`, `e`.`color_value`, `e`.`size`, `e`.`size_value`, `e`.`load_type`, `e`.`load_type_value` FROM `catalog_product_flat_1` AS `e` WHERE (e.status = 1) AND (((e.visibility = '3') OR (e.visibility = '2') OR (e.visibility = '4'))) AND (((e.status = '1'))) ORDER BY `cat_index_position` ASC, `e`.`entity_id` ASC LIMIT 4

";i:1;s:3865:"#0 /home/dugun/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/dugun/public_html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/dugun/public_html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/dugun/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `e`.`ent...', Array)
#4 /home/dugun/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `e`.`ent...', Array)
#5 /home/dugun/public_html/lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `e`.`ent...', Array)
#6 /home/dugun/public_html/lib/Varien/Data/Collection/Db.php(740): Zend_Db_Adapter_Abstract->fetchAll('SELECT `e`.`ent...', Array)
#7 /home/dugun/public_html/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(1046): Varien_Data_Collection_Db->_fetchAll('SELECT `e`.`ent...')
#8 /home/dugun/public_html/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(871): Mage_Eav_Model_Entity_Collection_Abstract->_loadEntities(false, false)
#9 /home/dugun/public_html/lib/Varien/Data/Collection.php(741): Mage_Eav_Model_Entity_Collection_Abstract->load()
#10 /home/dugun/public_html/app/design/frontend/knock/default/template/widget/grid.phtml(54): Varien_Data_Collection->getIterator()
#11 /home/dugun/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/dugun/pub...')
#12 /home/dugun/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/knock/...')
#13 /home/dugun/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#14 /home/dugun/public_html/app/code/local/Meigee/Thememanager/Block/Widget/Products.php(32): Mage_Core_Block_Template->_toHtml()
#15 /home/dugun/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Meigee_Thememanager_Block_Widget_Products->_toHtml()
#16 /home/dugun/public_html/app/code/core/Mage/Widget/Model/Template/Filter.php(76): Mage_Core_Block_Abstract->toHtml()
#17 [internal function]: Mage_Widget_Model_Template_Filter->widgetDirective(Array)
#18 /home/dugun/public_html/lib/Varien/Filter/Template.php(163): call_user_func(Array, Array)
#19 /home/dugun/public_html/app/code/core/Mage/Core/Model/Email/Template/Filter.php(560): Varien_Filter_Template->filter('{{widget type="...')
#20 /home/dugun/public_html/app/code/core/Mage/Cms/Block/Block.php(69): Mage_Core_Model_Email_Template_Filter->filter('{{widget type="...')
#21 /home/dugun/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Cms_Block_Block->_toHtml()
#22 /home/dugun/public_html/app/design/frontend/knock/default/template/widget/tabs.phtml(10): Mage_Core_Block_Abstract->toHtml()
#23 /home/dugun/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/dugun/pub...')
#24 /home/dugun/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/knock/...')
#25 /home/dugun/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#26 /home/dugun/public_html/app/code/local/Meigee/Knock/Block/Widget/Tabs.php(8): Mage_Core_Block_Template->_toHtml()
#27 /home/dugun/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Meigee_Knock_Block_Widget_Tabs->_toHtml()
#28 /home/dugun/public_html/app/code/core/Mage/Widget/Model/Template/Filter.php(76): Mage_Core_Block_Abstract->toHtml()
#29 [internal function]: Mage_Widget_Model_Template_Filter->widgetDirective(Array)
#30 /home/dugun/public_html/lib/Varien/Filter/Template.php(163): call_user_func(Array, Array)
#31 /home/dugun/public_html/app/code/core/Mage/Core/Model/Email/Template/Filter.php(560): Varien_Filter_Template->filter('";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"english";}

**Comment by Marvin-Magmodules** [comment]
Not related to the Mollie module, looks like an issue with the category index (untouched by Mollie Module).
