### ISSUE TITLE
Mollie submodule

### ISSUE THREAD

**Issue by hans2103** [mollie/Magento#58]
I'm installing mollie using composer.
Since lib/Mollie is a submodule I cannot install Mollie/Magento using composer.
Can you undo lib/Mollie as a submodule?

**Comment by ottonet** [comment]
@hans2103 seems the only thing missing is a simple symlink between the lib folder and the actual library. If you add something like `ln -rs vendor/mollie/mollie-api-php/src .modman/mollie_magento/lib/Mollie` to your post-install commands, you should be able to use composer for your installation.

**Comment by Marvin-Magmodules** [comment]
Closing this issue as at this moment we don't have plans to undo this.
