### ISSUE TITLE
Mage registry key "_singleton/mpm/observer" already exists

### ISSUE THREAD

**Issue by WebBende** [mollie/Magento#59]
"Mage registry key "_singleton/mpm/observer" already exists"

Ik krijg deze foutmelding zodra ik de module bestanden heb gekopieerd en de cache heb verwijderd. Ook geprobeerd uit te loggen, maar vervolgens komt de login pagina niet meer tevoorschijn maar de error pagina die verwijst naar het error report waar bovenstaande error in te zien is.

Ik las eerder iets over firecheckout bij een oud issue, dat gebruiken wij ook in onze magento omgeving, maar ik kan er verder niet uit halen wat ik eventueel zou kunnen veranderen.

Ik hoor graag wat ik eventueel kan wijzigen zodat mollie werkt.

**Comment by rsjmeijer** [comment]
Ik heb exact hetzelfde probleem na een update van de bestanden.

de Cache verwijderen, uitloggen  en opnieuw inloggen helpt niet.

**Comment by Marvin-Magmodules** [comment]
This is a result of an update with compilation enabled. To get this fixed rerun compilation though admin or edit the includes/config.php and comment out both "define" lines at the end of the file by placing a # in front of them.
