### ISSUE TITLE
"Mage registry key "_singleton/mpm/observer" already exists" after update to latest mollie files

### ISSUE THREAD

**Issue by rsjmeijer** [mollie/Magento#61]
After an update to the latest mollie files, i get the error: "Mage registry key "_singleton/mpm/observer" already exists" on the adminpage. The frontpage is normal.

Only by diabeling the mollie module by ftp the admin page works again.

What to do??

**Comment by Marvin-Magmodules** [comment]
This is a result of an update with compilation enabled. To get this fixed rerun compilation though admin or edit the includes/config.php and comment out both "define" lines at the end of the file by placing a # in front of them.
