### ISSUE TITLE
wrong state used

### ISSUE THREAD

**Issue by downforce80** [mollie/Magento#63]
Mollie plug sets STATE to 'processing' if not payed yet!
STATE should be 'pending_payment'. After payment it should be 'processing'.

Other webservices are relying on the STATE in magento. 
This results in shipped orders which haven't been payed!

**Comment by pepijnblom** [comment]
We can confirm this. This also results in the following problem: if a comment is placed by a customer service agent in the backend the status is also changed to processing and the orders becomes "fully paid" in terms of state & status. This results in more orders being sent which haven't actually been paid yet.

**Comment by Marvin-Magmodules** [comment]
Issue is fixed in [4.4.0-Beta](https://github.com/mollie/Magento/releases/tag/v4.4.0). State is not touched directly by the Mollie module, only set dynamically as a result of the creation of an invoice.
