### ISSUE TITLE
Double pay orders

### ISSUE THREAD

**Issue by it-can** [mollie/Magento#64]
It is possible to double pay orders, when you know the url structure. Should there be an extra check before redirecting to Mollie to check to see if the order is already paid? If it is already paid then redirect back to the shop?

It should be possible to check to order total due...

```
$order->getBaseTotalDue()
```

if this returns 0 then there is no due, so it is paid...

**Comment by Marvin-Magmodules** [comment]
Extra checks have been implemented in [4.4.0-Beta](https://github.com/mollie/Magento/releases/tag/v4.4.0) to see if the order is already processed.
