### ISSUE TITLE
OSC - Payment method got reset every time the payment get updated via ajax

### ISSUE THREAD

**Issue by reinos** [mollie/Magento#65]
Hi there,

I notice a very anoying bug whenOSC installed, where orders created with the wrong payment method.

Assuming we have multple payment methods. Once on the onestepcheckout page and you filled in al your details, also a payment method, as example not the first in the list.
![image](https://user-images.githubusercontent.com/633730/32056736-bebb6fda-ba65-11e7-8c81-f84a81a3644a.png)

When clicking on the + sign of - sign next of the product list
![image](https://user-images.githubusercontent.com/633730/32056781-d954754e-ba65-11e7-8707-5993892adabd.png)
a new ajax call is made to update the totals. Also OSC update the payment method list. Because mollie extend that page to add the mollie payment method, there is some code added to the page to select the first payment method (https://github.com/mollie/Magento/blob/master/app/design/frontend/base/default/template/mollie/form/details.phtml#L39). In that check to select the first payment, there is no check to see if there is already a payment method selected. So this result that there is a new payment selected, but only on the front-end. 

When creating the order, yes customers didn't notice the change, the order is created with the first method selected as name in the backdend but the flow goes like the selected payment in the first image.

I fix this with a jquery call to check if there is a selected item in the payment list

```
if(jQuery('[name="payment[method]"]:checked').length == 0) {
	var element = document.findElementByAttribute('input', 'name', 'payment[method]');
	if (element && !element.checked) {
		element.focus();
		element.checked = true;
		payment.switchMethod(element.value);
	}
}
```

**Comment by Marvin-Magmodules** [comment]
We have removed all additional JS in the checkout in the [4.4.0-Beta](https://github.com/mollie/Magento/releases/tag/v4.4.0) release.
