### ISSUE TITLE
Always redirected to checkout/onepage/success when returning from mollie pay page

### ISSUE THREAD

**Issue by edwinljacobs** [mollie/Magento#66]
When a customer visits the mollie pay page (https://prnt.sc/hngthl) for a given payment method and decided to cancel the transaction. Then the ApiControllers returnAction method is invoked.

We find at line number 376:

// Get payment status from database ( `mollie_payments` )
				$oStatus = Mage::helper('mpm')->getStatusById($transactionId);
This status object is then checked as follows:
empty($oStatus['updated_at'] ) || $oStatus['bank_status'] === Mollie_Mpm_Model_Api::STATUS_PAID || $oStatus['bank_status'] === Mollie_Mpm_Model_Api::STATUS_PENDING)

When returning from mollie the following condition is true when the user decides to cancel the transaction
$oStatus['bank_status'] === Mollie_Mpm_Model_Api::STATUS_PENDING

When using mollies test environment this condition is also true when the user completes the transaction.
so it seems the no matter how the transaction unfolds it holds that

$oStatus['bank_status'] === Mollie_Mpm_Model_Api::STATUS_PENDING
when returning from mollie.

The issue is that there is no way to know in the returnAction method if the user decided to cancel the transaction. Later on in the returnAction method the user gets redirected to the success page, triggering all kinds analytics events that should only be registered for completed orders.

I checked which params are available when entering the method returnAction its just the order id and utm_nooverride=1. We want to be able to redirect the user to a different page if he or she decided to cancel the transaction (maybe back to the cart).

**Comment by Marvin-Magmodules** [comment]
This part has been completely rewritten in [4.4.0-Beta](https://github.com/mollie/Magento/releases/tag/v4.4.0). Cancelation results in a redirect to the cart instead of the checkout success.
