### ISSUE TITLE
Afrondingsverschil

### ISSUE THREAD

**Issue by i6media** [mollie/Magento#68]
Hi,

Wij werken in Magento 1.9 met 4 cijfers achter de komma. Prijzen van producten worden excl. BTW ingevoerd om zo op mooie ronde prijzen incl. BTW uit te komen (zoals € 49,50).

Nadeel is dat ook order totals worden afgerond op 4 cijfers achter de komma. Soms hebben we dan grand_totals van € 18,4501

Mollie rekent netjes € 18,45 af, maar bij de webhook wordt deze niet op 'betaald' gezet, vanwege een verschil van € 0,0001.

Oplossing is om het volgende aan te passen in de Mollie plugin:

`if ($paymentData->amount == $order->getGrandTotal()) {`

naar:

`if ($paymentData->amount == round($order->getGrandTotal(),2) ) {`

in bestand:

`/app/code/community/Mollie/Mpm/Model/Api.php`

Is het mogelijk dat bij een volgende release dit geïmplementeerd kan worden?

**Comment by Marvin-Magmodules** [comment]
Snap de issue, zullen dit van de week meenemen in de final van 4.4.0

**Comment by Marvin-Magmodules** [comment]
Verwerkt in de nieuwe [v4.4.0](https://github.com/mollie/Magento/releases/tag/v4.4.0) release.
