### ISSUE TITLE
Overboeking wordt meteen geaccordeerd(!)

### ISSUE THREAD

**Issue by unxsist** [mollie/Magento#69]
Hi,

Er doet zich in 4.4.0 een serieus probleem omtrent overboekingen voor. Indien een klant deze betaalmethode kiest, kent de module na het plaatsen van de order meteen de "Processing" (oftewel betaald) status toe. Dit is voor alle online betalingen prima, maar een overboeking moet juist worden geaccordeerd via de callback vanuit Mollie nadat deze succesvol een betaling heeft geregistreerd.

Zie onderstaande screenshots:

![schermafbeelding 2018-03-12 om 11 15 30](https://user-images.githubusercontent.com/210652/37278026-bc004ae4-25e6-11e8-84ff-f9d8fdb15a8f.png)

![schermafbeelding 2018-03-12 om 11 15 35](https://user-images.githubusercontent.com/210652/37278034-c0fd5168-25e6-11e8-8a64-6b91a4be195b.png)

**Comment by Marvin-Magmodules** [comment]
Idd hij was gekoppeld aan de default status van processing in plaats van pending. Is aangepast, zal vanmiddag worden meegenomen in de final.

**Comment by Marvin-Magmodules** [comment]
Merged in de nieuwe [v4.4.0](https://github.com/mollie/Magento/releases/tag/v4.4.0) release.
