### ISSUE TITLE
Popup stays open when you select a payment

### ISSUE THREAD

**Issue by reinos** [mollie/Magento#71]
Using the latest version of the module 4.4.x i get this fault on the front-end

![image](https://user-images.githubusercontent.com/633730/37963165-bb1f5a24-31bd-11e8-8697-42ae438b4acb.png)

Once selected a method, the popups keep open.

I uploaded all files correctly.

**Comment by Frank-Magmodules** [comment]
Hi @reinos ,

Thanks for your message, seems a conflict in your checkout with your theme but can you please sent me your store URL where this issue appears to frank@magmodules.eu so we can check this for you?

Thanks,

Frank

**Comment by Frank-Magmodules** [comment]
After investigating together with the client this seems to be an issue in the specific checkout layout, not in the Extension. Topic can be closed.
