### ISSUE TITLE
No success page through mobile banking app

### ISSUE THREAD

**Issue by GetMagented** [mollie/Magento#72]
When checking out on a mobile phone we have an issue that the customer will not go to Success page, but to checkout/cart. The order is paid succesful and is put on Processing, so that's OK.

However, when customers go to the cart instead of checkout page, they are not sure if the order is paid succesfully. Also, the transaction is not put in Google Analytics. 

My guess is that the problem occurs due to the fact that the mobile banking app is opening a new browser tab. For example, on my iPhone I'm using Chrome to place an order. When I go to the KNAB Banking app and I pay, the KNAB app will open a new Safari Private tab and go to checkout/success. However, because it's a new browser with a private tab, there is no session stored and Magento will redirect to an empty checkout/cart instead.

**Comment by Marvin-Magmodules** [comment]
Hi Chris, thanks for the detailed description, understand the issue, will do some investigation and will come back to you.

**Comment by willemstuursma** [comment]
You can forward the session in the return URL - but this will expose all your session ids to any MITM and to Mollie of course. 
If the KNAB app is opening a _private_ tab, that seems like a bug there. The session will never be continued from before the app.

**Comment by GetMagented** [comment]
I didn't test this, but I suspect that the KNAB app is not necessarily opening a private tab, but it is using Safari as it's default browser (on my phone at least...) and Safari will open the tab that was last used. So if you are in normal mode it will open a normal tab, if you had a private tab open it will open a new private tab.

Don't know how other banks do this, but of course it would be best if KNAB would continue in the browser that was used during checkout. However, if you are shopping in a private tab the same problem will occur.

**Comment by willemstuursma** [comment]
On iOS it works by just sending the URL to the system and letting iOS deal with it right? So the app can't affect this. It's been a while since I worked on iOS.

**Comment by Marvin-Magmodules** [comment]
Did some extra testing on other banking apps on iOs and looks like this is indeed dealt by the system as both are opened by the default browser (Safari) and not the browser that was used for placing the order, which results in missing session data. Only using the Order ID is not sufficient to redirect the user to the checkout success or cart, so we need to add some extra data to the redirect url for validation. @willemstuursma can you shed some light on this? Is there a way to get the payment id in the redirect url or do we need to create a random string and add this to the metadata & redirect url? Or maybe some other solution.

**Comment by willemstuursma** [comment]
> Is there a way to get the payment id in the redirect url.

No.

You must add it to the metadata somehow.

**Comment by Marvin-Magmodules** [comment]
ok.

**Comment by Marvin-Magmodules** [comment]
@GetMagented issue has been resolved in [release 4.5.4](https://github.com/mollie/Magento/releases/tag/v4.5.4).
