### ISSUE TITLE
Orders not cancelled in sales_flat_order_grid

### ISSUE THREAD

**Issue by GetMagented** [mollie/Magento#73]
We have a strange problem since the update of this Mollie Magento extension. When the order is cancelled in Mollie, the order status is updated to 'cancelled' in Magento. However, in the admin order grid the status of the order is still 'pending'. So only on order detail page the order is cancelled.

When I search the table in PHPmyadmin I also still see status 'pending' instead of 'cancelled' for these orders. So it looks like the extension is not updating the "sales_flat_order_grid" table?

**Comment by Marvin-Magmodules** [comment]
Was not fully able to get this reproduced, but looks like the cancelOrder() function was bypassing an event. Can you check if this is resolved? See: [branch 4.4.1](https://github.com/mollie/Magento/tree/4.4.1)

**Comment by GetMagented** [comment]
Thanks for looking into it. I updated to 4.4.1 but unfortunately the problem has not been solved. Orders that are expired or cancelled still show up as 'Pending' in the grid and in the Order's tab on Customer profile page in backend.

**Comment by Marvin-Magmodules** [comment]
Can you [contact](https://www.magmodules.eu/contact-us.html) me to exchange some urls and logins (if possible) so we can look into this?

**Comment by HRR1337** [comment]
We also notice an big increase in 'payment pending' since 7 april.

**Comment by GetMagented** [comment]
I've setup a staging environment and emailed you the login details so you can reproduce the problem.

**Comment by Marvin-Magmodules** [comment]
Issue caused by observer from other module, not related to Mollie module.
