### ISSUE TITLE
Payment method icons have disappeared

### ISSUE THREAD

**Issue by JerVoo** [mollie/Magento#84]
After upgrading to version 4.5.1, the payment method icons, which were available up to 4.3.0, have disappeared. These icons were a welcome visual aid for our customers, since it doesn't require any reading.

Will these icons be added again in the future?

![image](https://user-images.githubusercontent.com/4249421/40421916-c761d076-5e8d-11e8-94c4-f3994172f146.png)

**Comment by Marvin-Magmodules** [comment]
We are not able to reproduce this error. However looking at your screenshot it looks like the frontend template files have been overwritten on theme level (some text is added). Can you double check this?

**Comment by JerVoo** [comment]
@Marvin-Magmodules  The added text is done through CSS.

There is, however, a conflict between the Mollie extension and other possible payment extensions.

We're using the Aheadworks Points-extension, which partially overrides OneStepCheckout's `payment_methods.phtml` template. The changes are minimal, however required for this other payment method to work.

---

If I'm correct the images will be added when `$method->getTitle()` is being called. Nothing has changed when it comes to displaying the method title, so in my opinion the image should be displayed correctly. This has worked without any problem for version 4.3.0 of the extension, however after upgrading to 4.5.0 it's no longer working.

**Comment by Marvin-Magmodules** [comment]
@JerVoo in 4.3.0 this was done by javascript, which was mixing up some of the OPC's, so we removed this code and add this using [getMethodLabelAfterHtml](https://github.com/mollie/Magento/blob/master/app/code/community/Mollie/Mpm/Block/Payment/Form.php#L55) to make this more compatible. Can you drop me a link to the webshop [here](https://www.magmodules.eu/contact-us.html) so we can check the source?

**Comment by Marvin-Magmodules** [comment]
Hi @JerVoo any update on this?

**Comment by JerVoo** [comment]
Currently not. I'll get back to this (and contact you through the support page) on Monday. Another project got in the way.

**Comment by Marvin-Magmodules** [comment]
Hi @JerVoo I'm closing this issue now due to inactivity and not able to reproduce. Feel free to reopen this issue once you have the time to sent us some links. Also please check system.log for error and if installed by modman make sure you use `copy` instead of `symlink` as symlink for frontend theme files is not possible anymore since SUPEE-9767.
