### ISSUE TITLE
not showing logo's 

### ISSUE THREAD

**Issue by vdvcoder** [mollie/Magento#88]
Latest version 4.5.3 not showing logo's when activate it in backoffice.
![screenshot_3](https://user-images.githubusercontent.com/13916116/41150873-65960630-6b0f-11e8-931b-1c141385cd5d.png)

**Comment by Frank-Magmodules** [comment]
Hi @vdvcoder ,

Can you check system.log for errors and if installed by Modman make sure you use copy instead of symlink as symlink for frontend theme files is not possible anymore since SUPEE-9767.

**Comment by AlexanderHuyghebaert** [comment]
@Frank-Magmodules : the extension is installed without symlinks, but the shop is using onestepcheckout. can this be reason?

**Comment by Frank-Magmodules** [comment]
Hi @AlexanderHuyghebaert , it should work with the Onestepcheckout but surely we can take a look with you.  Can you contact us through https://www.magmodules.eu/contact-us.html so we can investigate this for you?

**Comment by Frank-Magmodules** [comment]
We’ve just reviewed this issue together with the OneStepCheckout Team and we’ve reproduced this issue on our dev-environment. We are currently working on a solution to get the payment images compatible with the OneStepCheckout extension, we will keep you up to date about the progress. Thank you for your patience.

**Comment by Frank-Magmodules** [comment]
Hi @AlexanderHuyghebaert , 

We had contact with the team of OneStepCheckout about this and they implemented the fix in their code but they are not going to release a new version on the short term so we've written a small guide with the solution for this problem. 

See the bottom of our [Troubleshooting guide.](https://github.com/mollie/Magento/wiki/Troubleshooting)

**Comment by AlexanderHuyghebaert** [comment]
@Frank-Magmodules : thank you for the follow-up!
