### ISSUE TITLE
Incomplete /lib folder is empty

### ISSUE THREAD

**Issue by henkvalk** [mollie/Magento#89]
After downloading the extension 4.5.3 The message API v2 is not installed will shown up in the backend. Your Wiki page tells me that the lib folder must be written to the root. When I look in the downloaded files the lib/Mollie/Mollie folder is empty. When I look into lib/Mollie/Mollie at Github, there will be shown a link to another repository.
Is this the reason why this won't download it into the zip-folder? 

Do we need to download that repositories manually?

**Comment by Frank-Magmodules** [comment]
HI @henkvalk ,

Maybe you've downloaded the files directly from the GitHub Repository, the /lib folder is not included there. Please download the full package from the release tab; https://github.com/mollie/Magento/releases, see step one on the "How to install & upgrade" section.

Frank

**Comment by henkvalk** [comment]
Hi @Frank-Magmodules Thanks for your quick response.

Maybe it is an Idea to create this link into the Wiki page and the README.md ?

**Comment by Frank-Magmodules** [comment]
Hi @henkvalk , Yes, the first line on the Wiki is already;

_Download the latest package from the release tab. Make sure the Package name is like mollie-magento.x.x.x.zip and shows the latest version number._

But i've changed this to a link now as well, thanks!

**Comment by Frank-Magmodules** [comment]
@henkvalk , can please close this issue or let me know it's solved now? Thanks, have a good weekend ahead.
