### ISSUE TITLE
$_canUserInternal change in 4.5.0 is killing our backend order input

### ISSUE THREAD

**Issue by loekvangool** [mollie/Magento#91]
`$_canUseInternal` was set to `false` in 4.5.0:

https://github.com/mollie/Magento/blob/v4.5.0/app/code/community/Mollie/Mpm/Model/Api.php#L72

This kills our ability to create orders in the backend (no other payment methods are enabled). We will have to patch to make back-end orders possible again. We could also go with the internal Bank Transfer method, but we cannot prevent Magento from displaying it in the front-end, and in the front-end we only want Mollie payment methods to display. Is there any specific reason for this change? Why not make it configurable?

**Comment by loekvangool** [comment]
@Frank-Magmodules understood, but please be aware that Magento *blocks* the order creation if no payment method can be selected. The upcoming payment link method seems the right approach, and I would have waited to take this step until it is finished, honestly.

Arguably it is a Magento limitation that payment methods cannot be disabled for the front-end.

**Comment by Marvin-Magmodules** [comment]
Hi @loekvangool you can limit payment methods to admin by setting $_canUseCheckout to false.

**Comment by loekvangool** [comment]
Thanks @Marvin-Magmodules. That's just another core hack, or at least a core override. We prefer not to have those unless absolutely necessary.

**Comment by Marvin-Magmodules** [comment]
Hi @loekvangool was not referring to a core module, you can easily create this as a custom method.
